# All detection rules live here. Edit & save; bot reloads in ~5s.

timeframes:
  "15m":
    delta_pct: 1.6        # % move vs previous closed 15m candle
    vol_mult: 3.0         # volume multiple vs EMA(volume)
    min_notional: 80000   # USDT traded in the candle
    ema_len: 20           # EMA length for volume
    cooldown_min: 20      # cooldown minutes per symbol/tf
  "30m":
    delta_pct: 2.4
    vol_mult: 2.4
    min_notional: 120000
    ema_len: 24
    cooldown_min: 30
  "1h":
    delta_pct: 3.5
    vol_mult: 2.0
    min_notional: 200000
    ema_len: 30
    cooldown_min: 60

tiers:
  A:
    vol_mult_adj: -0.6    # big caps: lower mult, higher notional
    min_notional: 300000
    delta_pct_adj: 0.0
  B:
    vol_mult_adj: 0.0
    min_notional: 120000
    delta_pct_adj: 0.0
  C:
    vol_mult_adj: 0.5     # small caps: stronger filter
    min_notional: 60000
    delta_pct_adj: 0.8

# Assign tiers to symbols (default = B if missing)
symbols:
  BTCUSDT: { tier: A }
  ETHUSDT: { tier: A }
  SOLUSDT: { tier: A }

quality_filters:
  min_body_ratio: 0.5     # candle body >= 50% of range
  max_spread_pct: 0.25    # skip if orderbook spread too high
  debounce_sec: 20        # signal must persist before firing
