# All detection rules live here. Edit & save; bot reloads in ~5s.

timeframes:
  "15m":
    delta_pct: 1.4        # was 1.6 (loosen a bit since new filters cut noise)
    vol_mult: 2.6         # was 3.0
    min_notional: 80000
    ema_len: 20
    cooldown_min: 20

  "30m":
    delta_pct: 2.2        # was 2.4
    vol_mult: 2.2         # was 2.4
    min_notional: 120000
    ema_len: 24
    cooldown_min: 30

  "1h":
    delta_pct: 3.2        # was 3.5
    vol_mult: 1.9         # was 2.0
    min_notional: 200000
    ema_len: 30
    cooldown_min: 60

tiers:
  A:
    vol_mult_adj: -0.6    # big caps: easier volume bar, higher notional
    min_notional: 300000
    delta_pct_adj: 0.0
  B:
    vol_mult_adj: 0.0
    min_notional: 120000
    delta_pct_adj: 0.0
  C:
    vol_mult_adj: 0.5     # small caps: stricter
    min_notional: 60000
    delta_pct_adj: 0.8

# Assign tiers to symbols (default = B if missing)
symbols:
  BTCUSDT: { tier: A }
  ETHUSDT: { tier: A }
  SOLUSDT: { tier: A }

quality_filters:
  min_body_ratio: 0.5
  max_spread_pct: 0.25
  debounce_sec: 20
